services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
    volumes:
      - bj-pgdata:/var/lib/postgresql

  # If you use another S3-compatible service in production, you can replace this MinIO configuration with the appropriate settings for that service.
  minio:
    image: minio/minio:latest
    ports:
      - "9222:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minioadmin}
    env_file:
      - .env
    restart: unless-stopped
    command: server /data
    volumes:
      - bj-minio_data:/data

  app:
    build: .
    ports:
      - "9220:3000"
    depends_on:
      - db
      - minio
    env_file:
      - .env
    restart: unless-stopped

volumes:
  bj-minio_data:
  bj-pgdata:
