services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "9221:5432" # postgres port
    restart: no
    volumes:
      - bj-pgdata:/var/lib/postgresql

  minio:
    image: minio/minio:latest
    ports:
      - "9222:9000" # minio api
      - "9223:9001" # minio webui console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    restart: no
    command: server /data --console-address ":9001"
    volumes:
      - bj-minio_data:/data

volumes:
  bj-minio_data:
  bj-pgdata: